name: libo

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Golang setup
      uses: actions/setup-go@v6
      with:
        go-version: '1.24' 

    - name: golangci-lint 
      uses: golangci/golangci-lint-action@v8 
      with:
        version: v2.1

    - name: Tests
      run: go test -v ./...

